name: Deploy to DigitalOcean
env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH passphrase
        env:
          SSH_PASSPHRASE: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@164.92.120.37 'cd /var/www/html/wp-content/themes/digital-newspaper && git pull'
