name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 164.92.120.37
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22
          script: |
            cd /var/www/html/wp-content/themes/<theme_name>
            git pull

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@164.92.120.37 'cd /var/www/html/wp-content/themes/digital-newspaper && git pull'
